import pathlib

from job_search.posting import Posting

HEADER = (
    "| Job Title | Company | Location | URL | Source | Fetched | Fit Score | Rationale |\n"
    "|---|---|---|---|---|---|---|---|\n"
)


def write_internships_md(path, postings: list[Posting]) -> None:
    ordered = sorted(postings, key=lambda p: -(p.fit_score or 0))
    lines = [
        "# Fall 2026 Data Science / Analyst / BI Internship Search\n\n",
        f"Auto-generated by job_search.py. {len(ordered)} postings within 20 miles of home or remote.\n\n",
        HEADER,
    ]
    for p in ordered:
        title = (p.title or "").replace("|", "/")
        company = (p.company or "").replace("|", "/")
        location = (p.location or "").replace("|", "/")
        url = (p.url or "").replace("|", "/")
        rationale = (p.rationale or "").replace("|", "/")
        # str(float) round-trips exactly (float(str(x)) == x), unlike a fixed
        # .2f format, which can truncate a score across the 30% cutoff and
        # make rank's in-memory qualifying count disagree with a value
        # re-parsed from this file later (e.g. by the apply playbook).
        score = str(p.fit_score) if p.fit_score is not None else "-"
        lines.append(
            f"| {title} | {company} | {location} | {url} | {p.source} | "
            f"{p.fetched_date} | {score} | {rationale} |\n"
        )
    pathlib.Path(path).write_text("".join(lines), encoding="utf-8")


def parse_internships_md(path) -> list[Posting]:
    postings = []
    for line in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if not cells or cells[0] == "Job Title":
            continue
        if len(cells) < 6:
            continue
        title, company, location, url, source, fetched = cells[:6]
        fit_score = None
        rationale = None
        if len(cells) >= 8:
            score_str = cells[6]
            if score_str not in ("-", ""):
                fit_score = float(score_str)
            rationale = cells[7] or None
        postings.append(Posting(title=title, company=company, location=location, url=url,
                                 source=source, fetched_date=fetched,
                                 fit_score=fit_score, rationale=rationale))
    return postings
